User.create(name: "tori", password: "test", username: "Tori")

20.times do
    Log.create(user_id: 1)
end

Emotion.create(log_id: 1, name: "Fear",         intensity: 2 )
Emotion.create(log_id: 1, name: "Anger",        intensity: 3 )
Emotion.create(log_id: 1, name: "Sadness",      intensity: 5 )
Emotion.create(log_id: 1, name: "Anxiety",      intensity: 7 )
Emotion.create(log_id: 1, name: "Happiness",    intensity: 4 )
Emotion.create(log_id: 1, name: "Peacefulness", intensity: 8 )
Emotion.create(log_id: 1, name: "Gratitude",    intensity: 2 )

Emotion.create(log_id: 2, name: "Fear",         intensity: 3 )
Emotion.create(log_id: 2, name: "Anger",        intensity: 3 )
Emotion.create(log_id: 2, name: "Sadness",      intensity: 6 )
Emotion.create(log_id: 2, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 2, name: "Happiness",    intensity: 0 )
Emotion.create(log_id: 2, name: "Peacefulness", intensity: 2 )
Emotion.create(log_id: 2, name: "Gratitude",    intensity: 6 )

Emotion.create(log_id: 3, name: "Fear",         intensity: 5 )
Emotion.create(log_id: 3, name: "Anger",        intensity: 6 )
Emotion.create(log_id: 3, name: "Sadness",      intensity: 4 )
Emotion.create(log_id: 3, name: "Anxiety",      intensity: 1 )
Emotion.create(log_id: 3, name: "Happiness",    intensity: 10)
Emotion.create(log_id: 3, name: "Peacefulness", intensity: 0 )
Emotion.create(log_id: 3, name: "Gratitude",    intensity: 2 )

Emotion.create(log_id: 4, name: "Fear",         intensity: 1 )
Emotion.create(log_id: 4, name: "Anger",        intensity: 2 )
Emotion.create(log_id: 4, name: "Sadness",      intensity: 3 )
Emotion.create(log_id: 4, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 4, name: "Happiness",    intensity: 5 )
Emotion.create(log_id: 4, name: "Peacefulness", intensity: 6 )
Emotion.create(log_id: 4, name: "Gratitude",    intensity: 7 )

Emotion.create(log_id: 5, name: "Fear",         intensity: 7 )
Emotion.create(log_id: 5, name: "Anger",        intensity: 6 )
Emotion.create(log_id: 5, name: "Sadness",      intensity: 5 )
Emotion.create(log_id: 5, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 5, name: "Happiness",    intensity: 3 )
Emotion.create(log_id: 5, name: "Peacefulness", intensity: 2 )
Emotion.create(log_id: 5, name: "Gratitude",    intensity: 1 )

Emotion.create(log_id: 6, name: "Fear",         intensity: 2 )
Emotion.create(log_id: 6, name: "Anger",        intensity: 3 )
Emotion.create(log_id: 6, name: "Sadness",      intensity: 5 )
Emotion.create(log_id: 6, name: "Anxiety",      intensity: 7 )
Emotion.create(log_id: 6, name: "Happiness",    intensity: 4 )
Emotion.create(log_id: 6, name: "Peacefulness", intensity: 8 )
Emotion.create(log_id: 6, name: "Gratitude",    intensity: 2 )

Emotion.create(log_id: 7, name: "Fear",         intensity: 3 )
Emotion.create(log_id: 7, name: "Anger",        intensity: 3 )
Emotion.create(log_id: 7, name: "Sadness",      intensity: 6 )
Emotion.create(log_id: 7, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 7, name: "Happiness",    intensity: 0 )
Emotion.create(log_id: 7, name: "Peacefulness", intensity: 2 )
Emotion.create(log_id: 7, name: "Gratitude",    intensity: 6 )

Emotion.create(log_id: 8, name: "Fear",         intensity: 5 )
Emotion.create(log_id: 8, name: "Anger",        intensity: 6 )
Emotion.create(log_id: 8, name: "Sadness",      intensity: 4 )
Emotion.create(log_id: 8, name: "Anxiety",      intensity: 1 )
Emotion.create(log_id: 8, name: "Happiness",    intensity: 10)
Emotion.create(log_id: 8, name: "Peacefulness", intensity: 0 )
Emotion.create(log_id: 8, name: "Gratitude",    intensity: 2 )

Emotion.create(log_id: 9, name: "Fear",         intensity: 1 )
Emotion.create(log_id: 9, name: "Anger",        intensity: 2 )
Emotion.create(log_id: 9, name: "Sadness",      intensity: 3 )
Emotion.create(log_id: 9, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 9, name: "Happiness",    intensity: 5 )
Emotion.create(log_id: 9, name: "Peacefulness", intensity: 6 )
Emotion.create(log_id: 9, name: "Gratitude",    intensity: 7 )

Emotion.create(log_id: 10, name: "Fear",         intensity: 7 )
Emotion.create(log_id: 10, name: "Anger",        intensity: 6 )
Emotion.create(log_id: 10, name: "Sadness",      intensity: 5 )
Emotion.create(log_id: 10, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 10, name: "Happiness",    intensity: 3 )
Emotion.create(log_id: 10, name: "Peacefulness", intensity: 2 )
Emotion.create(log_id: 10, name: "Gratitude",    intensity: 1 )

Emotion.create(log_id: 11, name: "Fear",         intensity: 2 )
Emotion.create(log_id: 11, name: "Anger",        intensity: 3 )
Emotion.create(log_id: 11, name: "Sadness",      intensity: 5 )
Emotion.create(log_id: 11, name: "Anxiety",      intensity: 7 )
Emotion.create(log_id: 11, name: "Happiness",    intensity: 4 )
Emotion.create(log_id: 11, name: "Peacefulness", intensity: 8 )
Emotion.create(log_id: 11, name: "Gratitude",    intensity: 2 )

Emotion.create(log_id: 12, name: "Fear",         intensity: 3 )
Emotion.create(log_id: 12, name: "Anger",        intensity: 3 )
Emotion.create(log_id: 12, name: "Sadness",      intensity: 6 )
Emotion.create(log_id: 12, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 12, name: "Happiness",    intensity: 0 )
Emotion.create(log_id: 12, name: "Peacefulness", intensity: 2 )
Emotion.create(log_id: 12, name: "Gratitude",    intensity: 6 )

Emotion.create(log_id: 13, name: "Fear",         intensity: 5 )
Emotion.create(log_id: 13, name: "Anger",        intensity: 6 )
Emotion.create(log_id: 13, name: "Sadness",      intensity: 4 )
Emotion.create(log_id: 13, name: "Anxiety",      intensity: 1 )
Emotion.create(log_id: 13, name: "Happiness",    intensity: 10)
Emotion.create(log_id: 13, name: "Peacefulness", intensity: 0 )
Emotion.create(log_id: 13, name: "Gratitude",    intensity: 2 )

Emotion.create(log_id: 14, name: "Fear",         intensity: 1 )
Emotion.create(log_id: 14, name: "Anger",        intensity: 2 )
Emotion.create(log_id: 14, name: "Sadness",      intensity: 3 )
Emotion.create(log_id: 14, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 14, name: "Happiness",    intensity: 5 )
Emotion.create(log_id: 14, name: "Peacefulness", intensity: 6 )
Emotion.create(log_id: 14, name: "Gratitude",    intensity: 7 )

Emotion.create(log_id: 15, name: "Fear",         intensity: 7 )
Emotion.create(log_id: 15, name: "Anger",        intensity: 6 )
Emotion.create(log_id: 15, name: "Sadness",      intensity: 5 )
Emotion.create(log_id: 15, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 15, name: "Happiness",    intensity: 3 )
Emotion.create(log_id: 15, name: "Peacefulness", intensity: 2 )
Emotion.create(log_id: 15, name: "Gratitude",    intensity: 1 )

Emotion.create(log_id: 16, name: "Fear",         intensity: 2 )
Emotion.create(log_id: 16, name: "Anger",        intensity: 3 )
Emotion.create(log_id: 16, name: "Sadness",      intensity: 5 )
Emotion.create(log_id: 16, name: "Anxiety",      intensity: 7 )
Emotion.create(log_id: 16, name: "Happiness",    intensity: 4 )
Emotion.create(log_id: 16, name: "Peacefulness", intensity: 8 )
Emotion.create(log_id: 16, name: "Gratitude",    intensity: 2 )

Emotion.create(log_id: 17, name: "Fear",         intensity: 3 )
Emotion.create(log_id: 17, name: "Anger",        intensity: 3 )
Emotion.create(log_id: 17, name: "Sadness",      intensity: 6 )
Emotion.create(log_id: 17, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 17, name: "Happiness",    intensity: 0 )
Emotion.create(log_id: 17, name: "Peacefulness", intensity: 2 )
Emotion.create(log_id: 17, name: "Gratitude",    intensity: 6 )

Emotion.create(log_id: 18, name: "Fear",         intensity: 5 )
Emotion.create(log_id: 18, name: "Anger",        intensity: 6 )
Emotion.create(log_id: 18, name: "Sadness",      intensity: 4 )
Emotion.create(log_id: 18, name: "Anxiety",      intensity: 1 )
Emotion.create(log_id: 18, name: "Happiness",    intensity: 10)
Emotion.create(log_id: 18, name: "Peacefulness", intensity: 0 )
Emotion.create(log_id: 18, name: "Gratitude",    intensity: 2 )

Emotion.create(log_id: 19, name: "Fear",         intensity: 1 )
Emotion.create(log_id: 19, name: "Anger",        intensity: 2 )
Emotion.create(log_id: 19, name: "Sadness",      intensity: 3 )
Emotion.create(log_id: 19, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 19, name: "Happiness",    intensity: 5 )
Emotion.create(log_id: 19, name: "Peacefulness", intensity: 6 )
Emotion.create(log_id: 19, name: "Gratitude",    intensity: 7 )

Emotion.create(log_id: 20, name: "Fear",         intensity: 7 )
Emotion.create(log_id: 20, name: "Anger",        intensity: 6 )
Emotion.create(log_id: 20, name: "Sadness",      intensity: 5 )
Emotion.create(log_id: 20, name: "Anxiety",      intensity: 4 )
Emotion.create(log_id: 20, name: "Happiness",    intensity: 3 )
Emotion.create(log_id: 20, name: "Peacefulness", intensity: 2 )
Emotion.create(log_id: 20, name: "Gratitude",    intensity: 1 )


